name: ie-bank-empty-professors-rg

on:
  push:
    paths:
      - 'scripts/**' # Trigger only with changes under folder 'scripts' or
      - '.github/workflows/ie-bank-empty-professors-rg.yml' # Trigger only with changes under folder '.github/workflows/ie-bank-empty-professors-rg.yml' or
  schedule:
    - cron: '59 21 * * *' # Trigger at 23:59 CEST (UTC + 2) every day
  workflow_dispatch: # Trigger manually

env:
  RESOURCE_GROUP_PROFESSORS: BCSAI2024-DEVOPS-PROFESSORS
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

jobs:
  remove-resource-groups:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main
    
    # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    # Empty resource group students professors
    - name: empty-resource-group-professors
      uses: azure/powershell@v2
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_PROFESSORS }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"